# Generated by Django 4.2 on 2023-05-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='areacomun',
            name='estado_reserva',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado')], default='Pendiente', max_length=20),
        ),
    ]
