# Generated by Django 4.2 on 2023-05-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_anuncio_areacomun_estado_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='estado_reserva',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado')], default='Disponible', max_length=20),
        ),
    ]
