# Generated by Django 4.2 on 2023-05-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_user_fecha_naci'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pagos_comunes',
            field=models.ManyToManyField(related_name='usuarios', to='myapp.pagocomun'),
        ),
    ]
