# Generated by Django 4.2 on 2023-05-31 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_user_pagos_comunes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multa',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
