# Generated by Django 4.2 on 2023-06-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_multa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gastos_comunes',
            field=models.ManyToManyField(blank=True, related_name='residentes', to='myapp.pagocomun'),
        ),
    ]
