# Generated by Django 4.2 on 2023-06-27 21:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_user_gastos_comunes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservarArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(default=datetime.date.today)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.areacomun')),
            ],
        ),
    ]
