# Generated by Django 4.2 on 2023-06-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_reservararea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='estado_reserva',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado')], max_length=20),
        ),
    ]
