# Generated by Django 4.2 on 2023-06-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_areacomun_estado_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='estado_reserva',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado')], default='Disponible', max_length=20),
        ),
        migrations.DeleteModel(
            name='ReservarArea',
        ),
    ]
