# Generated by Django 4.2 on 2023-06-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_areacomun_estado_reserva_delete_reservararea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='estado_pago',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
