# Generated by Django 4.2 on 2023-06-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_estado_pago_multa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20),
        ),
    ]
